fullnameOverride: "aws-efs-csi-driver"
replicaCount: 1

image:
  repository: amazon/aws-efs-csi-driver
  tag: "v1.4.8"
  pullPolicy: IfNotPresent

controller:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}
  affinity: {}

  serviceAccount:
    create: true
    name: efs-csi-controller-sa
    annotations: {}
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role
  healthPort: 9909
  regionalStsEndpoints: false
## Node daemonset variables

node:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
  nodeSelector: {}

  serviceAccount:
    create: true
    name: efs-csi-node-sa
    annotations: {}
    ## Enable if EKS IAM for SA is used
    #  eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/efs-csi-role

# storageClasses:
# - name: efs-sc-create-by-efs-csi-driver
#   annotations:
#     storageclass.kubernetes.io/is-default-class: "false"
#   mountOptions:
#   - tls
#   parameters:
#     provisioningMode: efs.csi.aws.com
#     fileSystemId: fs-1122aabb
#     directoryPerms: "700"
#     gidRangeStart: "1000"
#     gidRangeEnd: "2000"
#     basePath: "/dynamic_provisioning"
#   reclaimPolicy: Delete
#   volumeBindingMode: WaitForFirstConsumer
