
fullnameOverride: "vertical-pod-autoscaler"

admissionController:
  enabled: true
  replicaCount: 1
  image:
    repository: k8s.gcr.io/autoscaling/vpa-admission-controller
    tag: 0.12.0
    pullPolicy: IfNotPresent

  nodeSelector: {}
